name: LauncherJar
author: "HydrolienF"
description: 'Create a launcher for any jar app.'
branding:
  icon: 'play'
  color: 'orange'

on:
  pull_request:
    branches: [master]
    types: [closed]


inputs:
  project-name:  # id of input
    description: 'Name of your projet'
    required: true
  user-name:
    description: 'Name of the github user account'
    required: true
  launcher-jar-version:
    description: 'Version of launcher jar'
    required: true
  GITHUB_TOKEN:
    description: 'dollar{{ github.token }} from your action so that this action can add artifacts'
    required: true
  release-url:
    description: 'dollar{{ steps.create_release.outputs.upload_url }} from your action so that this action can add artifacts'
    required: true
  app-version:
    description: 'Version of the app & of the launcher'
    required: true
  uuid:
    description: 'Universally unique identifier for your app on Windows & Mac'
    required: false
    default: ''
  launcher-extension:
    description: 'The launcher extention: jar, exe, deb or dmg'
    required: false
    default: jar
  deb-maintainer-email:
    description: 'Email of the deb maintainer on Linux'
    required: false
    default: '...@gmail.com'
  gui:
    description: 'Does donwload show in GUI insted of CLI'
    required: false
    default: true
  runTimeImage:
    description: 'If define to "--runtime-image jlink/", it include only usefull module.'
    required: false
    default: '--runtime-image jlink/'
    # default : ''
  JRE_VERSION: 
    description: 'JRE version to use'
    required: false
    default: '18.0.8f'
  LAUNCH_AFTER_INSTALL:
    description: 'If true launch app after install'
    required: false
    default: true

env:
  JAVA_VERSION: '18'
  JAVA_DISTRIBUTION: 'temurin'


runs:
  using: "composite"
  steps:

  - uses: actions/setup-java@v3
    with:
      distribution: ${{ env.JAVA_DISTRIBUTION }}
      java-version: ${{ env.JAVA_VERSION }}

  - name: define main path
    shell: pwsh
    id: defineMainPath
    run: |
      $le = "${{ inputs.launcher-extension }}"
      if($le -eq "exe"){ $mainPath="D:/a/${{ inputs.project-name }}/${{ inputs.project-name }}/" }
      else { $mainPath="~/work/${{ inputs.project-name }}/${{ inputs.project-name }}/" }
      echo "mainPath=$mainPath" >> $GITHUB_OUTPUT
      echo $mainPath


  - name: download LauncherJar files
    uses: HydrolienF/usual@0.3.38
    with:
      args: 'download https://github.com/HydrolienF/LauncherJar/archive/refs/tags/${{ inputs.launcher-jar-version }}.zip temp.zip'
  
  # args is proably choose before steps start, so we can't use result of it.
  - name: unzip LauncherJar files
    if: inputs.launcher-extension=='exe'
    uses: HydrolienF/usual@0.3.38
    with:
      args: 'unzip temp.zip D:/a/${{ inputs.project-name }}/${{ inputs.project-name }}/'

  - name: unzip LauncherJar files
    if: inputs.launcher-extension!='exe'
    uses: HydrolienF/usual@0.3.38
    with:
      args: 'unzip temp.zip $HOME/work/${{ inputs.project-name }}/${{ inputs.project-name }}/'


  - name: create launcher as .jar
    shell: bash
    if: inputs.launcher-extension=='jar'
    run: |
      echo ${{ inputs.app-version }} > version.md
      echo ls -------------------------------------
      ls
      echo ----------------------------------------
      cd LauncherJar-${{ inputs.launcher-jar-version }}/
      echo '''
      {
          "userName": "${{ inputs.user-name }}",
          "projectName": "${{ inputs.project-name }}",
          "gui": ${{ inputs.gui }},
      }
      ''' > settings.json
      mvn -ntp versions:set -DnewVersion="${{ inputs.launcher-jar-version }}"
      mvn -ntp package
      mv target/LauncherJar-${{ inputs.launcher-jar-version }}.jar ${{ inputs.project-name }}Launcher.jar
      echo "choose name"
      nom=${{ inputs.project-name }}${{ inputs.app-version }}
      if [[ -e out/ ]]; then
        echo "clear out"
        rm out/ -fr
      fi

      mkdir -p out/$nom
      echo ls . -----------------------------------
      ls .
      echo ls out/$nom -----------------------------------
      ls 
      echo ----------------------------------------
      echo "cp .jar, README, LICENSE"
      mv ${{ inputs.project-name }}Launcher.jar out/$nom/.
      cp ../README* out/$nom/.
      cp ../LICENSE* out/$nom/.
      # cp ../version.md out/$nom/.
      file=../.mvn/jvm.config
      if test -f "$file"; then
        cp ../.mvn/jvm.config out/$nom/.
      fi
      echo ${{ inputs.JRE_VERSION }} > out/$nom/JREVersion.md

      echo "zip part"
      cd out/
      zip -qr ${{ inputs.project-name }}Launcher.zip $nom
      echo "delete directory"
      rm -fr $nom
      cd ..

      echo "-----------------------"
      ls -l out/
      echo "-----------------------"
      ls ..
      echo "-----------------------"
      cd ..
      mv LauncherJar-${{ inputs.launcher-jar-version }}/out/${{ inputs.project-name }}Launcher.zip ${{ inputs.project-name }}Launcher.zip


  - name: download jlink/
    if: inputs.launcher-extension=='exe' && inputs.runTimeImage!=''
    uses: HydrolienF/usual@0.3.38
    with:
      args: 'downloadAndUnzip https://github.com/HydrolienF/JRE/releases/download/${{ inputs.JRE_VERSION }}/jlink.zip D:/a/${{ inputs.project-name }}/${{ inputs.project-name }}/jlink/ jWindows/'
  - name: download jlink/
    if: inputs.launcher-extension=='deb'  && inputs.runTimeImage!=''
    uses: HydrolienF/usual@0.3.38
    with:
      args: 'downloadAndUnzip https://github.com/HydrolienF/JRE/releases/download/${{ inputs.JRE_VERSION }}/jlink.zip ~/work/${{ inputs.project-name }}/${{ inputs.project-name }}//jlink/ jLinux/'
  - name: download jlink/
    if: inputs.launcher-extension=='dmg' && inputs.runTimeImage!=''
    uses: HydrolienF/usual@0.3.38
    with:
      args: 'downloadAndUnzip https://github.com/HydrolienF/JRE/releases/download/${{ inputs.JRE_VERSION }}/jlink.zip ~/work/${{ inputs.project-name }}/${{ inputs.project-name }}//jlink/ jMac/'

  - name: download launcher as .zip unziped
    if: inputs.launcher-extension=='exe'
    uses: HydrolienF/usual@0.3.38
    with:
      args: 'downloadAndUnzip https://github.com/${{ inputs.user-name }}/${{ inputs.project-name }}/releases/download/${{ inputs.app-version }}/${{ inputs.project-name }}Launcher.zip D:/a/${{ inputs.project-name }}/${{ inputs.project-name }}/in/ ${{ inputs.project-name }}${{ inputs.app-version }}/'
  - name: download launcher as .zip unziped
    if: inputs.launcher-extension=='deb' || inputs.launcher-extension=='dmg'
    uses: HydrolienF/usual@0.3.38
    with:
      args: 'downloadAndUnzip https://github.com/${{ inputs.user-name }}/${{ inputs.project-name }}/releases/download/${{ inputs.app-version }}/${{ inputs.project-name }}Launcher.zip ~/work/${{ inputs.project-name }}/${{ inputs.project-name }}/in/ ${{ inputs.project-name }}${{ inputs.app-version }}/'


  - name: ls before create installer
    shell: pwsh
    if: inputs.launcher-extension!='jar'
    run: |
      echo "======================================================"
      echo "ls"
      ls
      echo "======================================================"
      echo "ls -r in/"
      Get-ChildItem -Recurse in/
      echo "======================================================"
      # echo "ls -r jlink/"
      # Get-ChildItem -Recurse jlink/
      # echo "======================================================"

  - name: winRessources/
    shell: pwsh
    if: inputs.launcher-extension=='exe'
    env:
      OS: 'Windows'
    run: mkdir winRessources


  - name: launch after install
    if: inputs.launcher-extension=='exe' && inputs.LAUNCH_AFTER_INSTALL
    uses: HydrolienF/usual@0.3.38
    with:
      args: 'download https://gist.githubusercontent.com/HydrolienF/97a6c94a0016adab590b55180b437712/raw/main.wxs D:/a/${{ inputs.project-name }}/${{ inputs.project-name }}/winRessources/main.wxs'


  - name: create exe installer
    shell: pwsh
    if: inputs.launcher-extension=='exe'
    env:
      OS: 'Windows'
    run: |
      # 1a line is the same for every OS, 2a is personalized by OS.
      jpackage --java-options "$(cat .mvn/jvm.config)" --input in -d out --name ${{ inputs.project-name }} --main-jar ${{ inputs.project-name }}Launcher.jar --main-class fr.formiko.launcherjar.Main --app-version ${{ inputs.app-version }} --description "Launcher of ${{ inputs.project-name }} v${{ inputs.app-version }}" --license-file LICENSE*  --vendor ${{ inputs.user-name }} ${{ inputs.runTimeImage }} -t ${{ inputs.launcher-extension }} `
      --icon tools/icon.ico --win-shortcut --win-menu --win-menu-group "${{ inputs.project-name }}" --win-upgrade-uuid "${{ inputs.uuid }}" --resource-dir winRessources
      # TODO fix addLaunchToMsi.js
      # cscript tools/addLaunchToMsi.js ${{ inputs.project-name }}-${{ inputs.app-version }}

  - name: create deb installer
    shell: pwsh
    if: inputs.launcher-extension=='deb'
    env:
      OS: 'Linux'
    run: |
      $packageName = echo $("${{ inputs.project-name }}".ToLower())
      mkdir debRessources/
      cp tools/icon.png debRessources/
      echo "$packageName" > debRessources/launcher.desktop
      echo "echo 'chmod'
      chmod -R 777 /opt/$packageName/
      echo 'Create shortcut. You can launch ${{ inputs.project-name }} in cmd line with:'
      echo $packageName
      sudo rm -f /bin/$packageName
      sudo ln -s /opt/$packageName/bin/${{ inputs.project-name }} /bin/$packageName" > debRessources/postinst
      echo "echo 'remove shortcut'
      sudo rm -f /bin/$packageName
      echo 'remove temp data'
      sudo rm -fr ~/.$packageName" > debRessources/postrm
      echo "======================================================"
      echo "ls debRessources/"
      ls debRessources/
      echo "======================================================"
      cat debRessources/launcher.desktop
      echo "======================================================"
      cat debRessources/postinst
      echo "======================================================"
      cat debRessources/postrm
      echo "======================================================"
      jpackage --java-options "$(cat .mvn/jvm.config)" --input in -d out --name ${{ inputs.project-name }} --main-jar ${{ inputs.project-name }}Launcher.jar --main-class fr.formiko.launcherjar.Main --app-version ${{ inputs.app-version }} --description "Launcher of ${{ inputs.project-name }} v${{ inputs.app-version }}" --license-file LICENSE*  --vendor ${{ inputs.user-name }} ${{ inputs.runTimeImage }} -t ${{ inputs.launcher-extension }} `
      --icon tools/icon.png --linux-package-name $packageName --linux-shortcut --linux-deb-maintainer ${{ inputs.deb-maintainer-email }} --linux-menu-group "Game;StrategyGame" --linux-app-category games --resource-dir debRessources/

  - name: create dmg installer
    shell: pwsh
    if: inputs.launcher-extension=='dmg'
    env:
      OS: 'Mac'
    run: |
      echo "Create dmg installer"
      # Force 1a version number to be 1 for mac (Mac don't accept 0 as 1a version number).
      $appVersion = "${{ inputs.app-version }}"
      if($appVersion[0] -eq '0'){
        $appVersion = '1'+$appVersion.Substring(1, $appVersion.length-1)
      }
      jpackage --java-options "$(cat .mvn/jvm.config)" --input in -d out --name ${{ inputs.project-name }} --main-jar ${{ inputs.project-name }}Launcher.jar --main-class fr.formiko.launcherjar.Main --app-version $appVersion --description "Launcher of ${{ inputs.project-name }} v${{ inputs.app-version }}" --license-file LICENSE*  --vendor ${{ inputs.user-name }} ${{ inputs.runTimeImage }} -t ${{ inputs.launcher-extension }} `
      --icon tools/icon.icns --mac-package-name $("${{ inputs.project-name }}".ToLower()) --mac-package-identifier "${{ inputs.uuid }}"

  - name: mv & ls after create installer
    shell: pwsh
    if: inputs.launcher-extension!='jar'
    run: |
      echo "======================================================"
      echo "ls out"
      ls out
      echo "======================================================"
      mv ./out/${{ inputs.project-name }}*.${{ inputs.launcher-extension }} ${{ inputs.project-name }}.${{ inputs.launcher-extension }}
      echo "======================================================"
      echo "ls"
      ls
      echo "======================================================"



  - name: upload artifact jar
    if: inputs.launcher-extension=='jar'
    uses: actions/upload-release-asset@v1
    with:
      upload_url: ${{ inputs.release-url }}
      asset_path: ${{ inputs.project-name }}Launcher.zip
      asset_name: ${{ inputs.project-name }}Launcher.zip
      asset_content_type: application/zip

  - name: upload artifact else
    if: inputs.launcher-extension!='jar'
    uses: actions/upload-release-asset@v1
    with:
      upload_url: ${{ inputs.release-url }}
      asset_path: ${{ inputs.project-name }}.${{ inputs.launcher-extension }}
      asset_name: ${{ inputs.project-name }}.${{ inputs.launcher-extension }}
      asset_content_type: application/${{ inputs.launcher-extension }}
